package com.bancstone.common.exception;

public class TestPicpMessageException {
	public static void firstException() throws PicpMessageException {
		throw new PicpMessageException(
				"\"firstException()\" method occurs an exception!");
	}

	/*
	 * public static void secondException() throws MySecondException { throw new
	 * MySecondException( "\"secondException()\" method occurs an exception!"); }
	 */
	public static void main(String[] args) {
		try {
			TestPicpMessageException.firstException();
			// TestPicpMessageException.secondException();
		} catch (PicpMessageException e1) {
			System.out.println("Exception: " + e1.fillInStackTrace());
			// e1.printStackTrace();
		} /*
		 * catch (MySecondException e2) { System.out.println("Exception: " +
		 * e2.getMessage()); // e2.printStackTrace(); }
		 */
	}
}
